///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace BApp2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the BApp2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("7bbdf5e8-72ba-4159-b959-166eee615871")]
    public partial class BApp2Repository : RepoGenBaseFolder
    {
        static BApp2Repository instance = new BApp2Repository();
        BApp2RepositoryFolders.ComThebappAndroidAppFolder _comthebappandroid;

        /// <summary>
        /// Gets the singleton class instance representing the BApp2Repository element repository.
        /// </summary>
        [RepositoryFolder("7bbdf5e8-72ba-4159-b959-166eee615871")]
        public static BApp2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public BApp2Repository() 
            : base("BApp2Repository", "/", null, 0, false, "7bbdf5e8-72ba-4159-b959-166eee615871", ".\\RepositoryImages\\BApp2Repository7bbdf5e8.rximgres")
        {
            _comthebappandroid = new BApp2RepositoryFolders.ComThebappAndroidAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7bbdf5e8-72ba-4159-b959-166eee615871")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ComThebappAndroid folder.
        /// </summary>
        [RepositoryFolder("8c3bcae4-2303-4314-bd1d-4f5865045768")]
        public virtual BApp2RepositoryFolders.ComThebappAndroidAppFolder ComThebappAndroid
        {
            get { return _comthebappandroid; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class BApp2RepositoryFolders
    {
        /// <summary>
        /// The ComThebappAndroidAppFolder folder.
        /// </summary>
        [RepositoryFolder("8c3bcae4-2303-4314-bd1d-4f5865045768")]
        public partial class ComThebappAndroidAppFolder : RepoGenBaseFolder
        {
            BApp2RepositoryFolders.IndexHtmlFolder _indexhtml;
            RepoItemInfo _visitsInfo;
            RepoItemInfo _signoutInfo;

            /// <summary>
            /// Creates a new ComThebappAndroid  folder.
            /// </summary>
            public ComThebappAndroidAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComThebappAndroid", "/mobileapp[@title='com.thebapp.android']", parentFolder, 30000, null, false, "8c3bcae4-2303-4314-bd1d-4f5865045768", "")
            {
                _indexhtml = new BApp2RepositoryFolders.IndexHtmlFolder(this);
                _visitsInfo = new RepoItemInfo(this, "VISITS", ".//dom[@page='menu.html']//section[#'sct-button']/a[@innertext='VISITS']", 30000, null, "c5832662-14cf-4901-862f-72b43bf38c07");
                _signoutInfo = new RepoItemInfo(this, "SignOut", ".//dom[@page='menu.html']//a[#'sign-out']", 30000, null, "5644e094-88bd-4d53-bb3f-f50a302fd5d6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8c3bcae4-2303-4314-bd1d-4f5865045768")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8c3bcae4-2303-4314-bd1d-4f5865045768")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The VISITS item.
            /// </summary>
            [RepositoryItem("c5832662-14cf-4901-862f-72b43bf38c07")]
            public virtual Ranorex.ATag VISITS
            {
                get
                {
                    return _visitsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The VISITS item info.
            /// </summary>
            [RepositoryItemInfo("c5832662-14cf-4901-862f-72b43bf38c07")]
            public virtual RepoItemInfo VISITSInfo
            {
                get
                {
                    return _visitsInfo;
                }
            }

            /// <summary>
            /// The SignOut item.
            /// </summary>
            [RepositoryItem("5644e094-88bd-4d53-bb3f-f50a302fd5d6")]
            public virtual Ranorex.ATag SignOut
            {
                get
                {
                    return _signoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SignOut item info.
            /// </summary>
            [RepositoryItemInfo("5644e094-88bd-4d53-bb3f-f50a302fd5d6")]
            public virtual RepoItemInfo SignOutInfo
            {
                get
                {
                    return _signoutInfo;
                }
            }

            /// <summary>
            /// The IndexHtml folder.
            /// </summary>
            [RepositoryFolder("536d5759-a659-46fc-9811-82a8ee1b53b0")]
            public virtual BApp2RepositoryFolders.IndexHtmlFolder IndexHtml
            {
                get { return _indexhtml; }
            }
        }

        /// <summary>
        /// The IndexHtmlFolder folder.
        /// </summary>
        [RepositoryFolder("536d5759-a659-46fc-9811-82a8ee1b53b0")]
        public partial class IndexHtmlFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rdbusInfo;
            RepoItemInfo _txtpasswordInfo;
            RepoItemInfo _txtusuarioInfo;
            RepoItemInfo _signinInfo;

            /// <summary>
            /// Creates a new IndexHtml  folder.
            /// </summary>
            public IndexHtmlFolder(RepoGenBaseFolder parentFolder) :
                    base("IndexHtml", ".//dom[@page='index.html']", parentFolder, 30000, null, false, "536d5759-a659-46fc-9811-82a8ee1b53b0", "")
            {
                _rdbusInfo = new RepoItemInfo(this, "RdbUs", ".//input[#'rdb-us']", 30000, null, "6d7c0c87-3602-422d-9276-b4a80e30bc4a");
                _txtpasswordInfo = new RepoItemInfo(this, "TxtPassword", ".//input[#'txtPassword']", 30000, null, "853f77dd-49c3-4cb3-9de0-65d328691167");
                _txtusuarioInfo = new RepoItemInfo(this, "TxtUsuario", ".//input[#'txtUsuario']", 30000, null, "8fe679e7-c77b-4e99-b1da-18fced5a9f2c");
                _signinInfo = new RepoItemInfo(this, "SIGNIN", ".//button[#'btn-login']/span[@innertext='SIGN IN']", 30000, null, "c8009586-1bb0-4a7d-89e8-ee867bd52912");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("536d5759-a659-46fc-9811-82a8ee1b53b0")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("536d5759-a659-46fc-9811-82a8ee1b53b0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RdbUs item.
            /// </summary>
            [RepositoryItem("6d7c0c87-3602-422d-9276-b4a80e30bc4a")]
            public virtual Ranorex.InputTag RdbUs
            {
                get
                {
                    return _rdbusInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RdbUs item info.
            /// </summary>
            [RepositoryItemInfo("6d7c0c87-3602-422d-9276-b4a80e30bc4a")]
            public virtual RepoItemInfo RdbUsInfo
            {
                get
                {
                    return _rdbusInfo;
                }
            }

            /// <summary>
            /// The TxtPassword item.
            /// </summary>
            [RepositoryItem("853f77dd-49c3-4cb3-9de0-65d328691167")]
            public virtual Ranorex.InputTag TxtPassword
            {
                get
                {
                    return _txtpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtPassword item info.
            /// </summary>
            [RepositoryItemInfo("853f77dd-49c3-4cb3-9de0-65d328691167")]
            public virtual RepoItemInfo TxtPasswordInfo
            {
                get
                {
                    return _txtpasswordInfo;
                }
            }

            /// <summary>
            /// The TxtUsuario item.
            /// </summary>
            [RepositoryItem("8fe679e7-c77b-4e99-b1da-18fced5a9f2c")]
            public virtual Ranorex.InputTag TxtUsuario
            {
                get
                {
                    return _txtusuarioInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtUsuario item info.
            /// </summary>
            [RepositoryItemInfo("8fe679e7-c77b-4e99-b1da-18fced5a9f2c")]
            public virtual RepoItemInfo TxtUsuarioInfo
            {
                get
                {
                    return _txtusuarioInfo;
                }
            }

            /// <summary>
            /// The SIGNIN item.
            /// </summary>
            [RepositoryItem("c8009586-1bb0-4a7d-89e8-ee867bd52912")]
            public virtual Ranorex.SpanTag SIGNIN
            {
                get
                {
                    return _signinInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SIGNIN item info.
            /// </summary>
            [RepositoryItemInfo("c8009586-1bb0-4a7d-89e8-ee867bd52912")]
            public virtual RepoItemInfo SIGNINInfo
            {
                get
                {
                    return _signinInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}